# --- IQL specific parameters ---

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

batch_size: 64
buffer_size: 1000
target_update_interval: 200

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: # Mixer becomes None

agent: "rnn_sarl"
agent_fc1: [128, 256]
agent_fc2: [256, 256]
rnn_hidden_dim: 528

obs_agent_id: False

name: "dqn_sarl"

use_cuda: False
use_tensorboard: True