# --- IQL specific parameters ---

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 5000

runner: "episode"

batch_size: 64
buffer_size: 2000
target_update_interval: 200

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: # Mixer becomes None

agent: "rnn_sarl"
agent_fc1: []
agent_fc2: []
rnn_hidden_dim: 128

obs_agent_id: False

name: "dqn_sarl"

use_cuda: False
use_tensorboard: True