env: owf

env_args:
  n_owt : 2
  lev : 3 # Fixed in this setting
  discount_reward : 0.95
  k_comp : # None
  state_obs : True
  state_d_rate : False
  obs_d_rate : True
  obs_multiple : False
  obs_all_d_rate : False
  campaign_cost : False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
test_interval: 10000
test_nepisode: 30
test_greedy: True
t_max: 1000000
