env: digital_twin

env_args:
  struct_type: "owf"
  n_comp: 10
  discount_reward: 0.95
  custom_param:
    lev:  3
  state_obs: True
  state_twin: False
  state_eps: False
  state_d_rate: False
  obs_twin: False
  obs_eps: False
  obs_d_rate: False
  obs_multiple: False
  obs_all_d_rate: False
  campaign_cost: True
  virtual_sensor: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
test_interval: 10000
test_nepisode: 1
test_greedy: True
t_max: 2050000
