env: struct_twin

env_args:
  n_comp: 3
  discount_reward: 0.95
  k_comp: 2
  state_obs: True
  state_twin: True
  state_d_rate: False
  state_alphas: False
  obs_twin: True
  obs_d_rate: False
  obs_multiple: False
  obs_all_d_rate: False
  obs_alphas: False
  env_correlation: False
  campaign_cost: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
test_interval: 10000
test_nepisode: 100
test_greedy: True
t_max: 2050000
